version: "3.8"

services:
  krayin-mysql:
    image: mysql:8.0
    container_name: krayin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: krayin
      MYSQL_USER: krayin
      MYSQL_PASSWORD: krayin
    ports:
      - "3306:3306"
    volumes:
      - krayin_mysql_data:/var/lib/mysql

  krayin-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: krayin-phpmyadmin
    restart: always
    environment:
      PMA_HOST: krayin-mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - krayin-mysql

  krayin-redis:
    image: redis:6.2
    container_name: krayin-redis
    restart: always
    ports:
      - "6379:6379"

  krayin-mailhog:
    image: mailhog/mailhog:latest
    container_name: krayin-mailhog
    restart: always
    ports:
      - "8025:8025"

  krayin-php-apache:
    image: ghcr.io/krayin/laravel-crm:latest
    container_name: krayin-php-apache
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: mysql
      DB_HOST: krayin-mysql
      DB_PORT: 3306
      DB_DATABASE: krayin
      DB_USERNAME: krayin
      DB_PASSWORD: krayin
      REDIS_HOST: krayin-redis
      MAIL_HOST: krayin-mailhog
      MAIL_PORT: 1025
    ports:
      - "8090:80"
    depends_on:
      - krayin-mysql
      - krayin-redis
      - krayin-mailhog

volumes:
  krayin_mysql_data:
