services:
  krayin-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: krayin
      MYSQL_USER: krayin
      MYSQL_PASSWORD: krayin
    ports:
      - "3306:3306"
    volumes:
      - krayin_mysql_data:/var/lib/mysql

  krayin-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: krayin-mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - krayin-mysql

  krayin-redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  krayin-mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "8025:8025"

  krayin-php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: krayin-php-apache
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ""
      DB_CONNECTION: mysql
      DB_HOST: krayin-mysql
      DB_PORT: 3306
      DB_DATABASE: krayin
      DB_USERNAME: krayin
      DB_PASSWORD: krayin
      REDIS_HOST: krayin-redis
      MAIL_MAILER: smtp
      MAIL_HOST: krayin-mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: admin@krayin.local
      MAIL_FROM_NAME: KrayinCRM
    ports:
      - "8090:80"
    volumes:
      - ./workspace:/var/www/html
    depends_on:
      - krayin-mysql
      - krayin-redis
      - krayin-mailhog
    command: >
      sh -c "
        if [ ! -f /var/www/html/.env ]; then
          cp .env.example .env && \
          php artisan key:generate && \
          composer install && \
          npm install && npm run dev && \
          php artisan migrate --force && \
          chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
        fi &&
        apache2-foreground
      "

volumes:
  krayin_mysql_data:
